### ISSUE TITLE
animatediff, cannot run

### ISSUE THREAD

**Issue by jasoncow007** [cocktailpeanut/animatediff.pinokio#1]
animatediff, cannot run,,,,error as
FetchError: request to https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors failed, reason: connect ECONNREFUSED 2600:9000:24ba:be00:17:b174:6d00:93a1:443 at ClientRequest. (C:\Users\jasoncow\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\node-fetch\lib\index.js:1491:11) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by jasoncow007** [comment]
click “install” just show ........connected!
also cannot download models

FetchError: request to https://civitai.com/api/download/models/57618 failed, reason: connect ETIMEDOUT 2a03:2880:f127:83:face:b00c:0:25de:443 at ClientRequest. (C:\Users\jasoncow\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\node-fetch\lib\index.js:1491:11) at ClientRequest.emit (node:events:513:28) at TLSSocket.socketErrorListener (node:_http_client:494:9) at TLSSocket.emit (node:events:513:28) at emitErrorNT (node:internal/streams/destroy:151:8) at emitErrorCloseNT (node:internal/streams/destroy:116:3) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
