### ISSUE TITLE
Installation and download models does not work.

### ISSUE THREAD

**Issue by CRCODE22** [cocktailpeanut/animatediff.pinokio#3]
Installation:

2/5) fs.download
{"url":"[https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors","path":"https://github.com/cocktailpeanut/sd-webui.pinokio.git/automatic1111/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors"%7D](https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors%22,%22path%22:%22https://github.com/cocktailpeanut/sd-webui.pinokio.git/automatic1111/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors%22%7D)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.dirname (node:path:654:5)
    at FS.download (C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\fs\index.js:166:21)
    at Api.run (C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\index.js:41:24)
    at Api.step (C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\index.js:485:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\index.js:671:25

Mode; download:

(1/3) fs.download
{"url":"[https://civitai.com/api/download/models/126470","path":"https://github.com/cocktailpeanut/sd-webui.pinokio.git/automatic1111/models/Stable-diffusion/majicmixRealistic_betterV2V25.safetensors"%7D](https://civitai.com/api/download/models/126470%22,%22path%22:%22https://github.com/cocktailpeanut/sd-webui.pinokio.git/automatic1111/models/Stable-diffusion/majicmixRealistic_betterV2V25.safetensors%22%7D)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.dirname (node:path:654:5)
    at FS.download (C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\fs\index.js:166:21)
    at Api.run (C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\index.js:41:24)
    at Api.step (C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\index.js:485:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\CRCODE22\AppData\Local\Programs\Pinokio\resources\app.asar\node_modules\pinokiod\kernel\api\index.js:671:25

**Comment by DouglasMoody** [comment]
@cocktailpeanut @pinokiocomputer
